### ISSUE TITLE
Non-minable asteroids keep replenishing and stacking up after minables are gone

### ISSUE THREAD

**Issue by ghost** [dirtyredz/Regenerative-Asteroids#1]
Issue:

After mining just the minable asteroids and re-entering the sector, asteroids will respawn no matter of the current non-minables. That is fine, however the next time it respawns it adds more unminable ones so they can keep stacking up when they are not mined.

**Comment by dirtyredz** [comment]
Check your config, there is an option to limit the number of NonMinableAsteroids in the sector:
Default is 1500
https://github.com/dirtyredz/Regenerative-Asteroids/blob/0d5a2851da2fa83aa97555c5338fc231b753aa70/mods/RegenerativeAsteroids/config/RegenerativeAsteroidsConfig.lua#L13

**Comment by ghost** [comment]
Yeah but what I saw is that they keep stacking up after regens if you only
mine the resource ones, going over the 1500 limit. Now im not 100% sure
anymore but I thought I saw more.

Op ma 28 mei 2018 17:15 schreef David McClain | Dirtyredz <
notifications@github.com>:
